# Generated by Django 2.1.4 on 2018-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_full_name', models.CharField(max_length=256)),
                ('extra_information', models.CharField(max_length=256)),
                ('upload_time', models.DateTimeField(verbose_name='date-time uploaded')),
            ],
        ),
    ]
